services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb-container
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - all
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wordpress-container
    build: ./requirements/wordpress/
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - all
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb

  nginx:
    container_name: nginx-container
    build: ./requirements/nginx
    networks:
      - all
    restart: on-failure
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress

networks:
  all:
    driver: bridge

volumes:
  wordpress_files:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /Users/${USER}/data/wordpress_files
      o: bind
  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /Users/${USER}/data/mariadb_data
      o: bind